spring:
  application:
    name: allen-upload
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #url: jdbc:p6spy:mysql://192.168.2.140:3306/iomp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/allen_upload?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: rootroot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 30MB

server:
  port: 9001

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    com:
      hdvon: DEBUG
    org:
      springframework:
        boot:
          autoconfigure: ERROR